lints.workspace = true

[package]
name = "lspelling-wordc"
version = "0.0.0"
edition = "2021"

[dependencies]
ruspell.workspace = true
tracing.workspace = true

ropey = "1"
tree-sitter = "0.23"

# Tree sitter grammars
# TODO: don't bundle?
tree-sitter-rust = "0.21"
